esphome:
  name: xiaomi-ir
  friendly_name: Xiaomi-IR
  platformio_options:
    extra_scripts: 
      - pre:pre_extra_script.py
    platform_packages:
      - framework-arduinoespressif32 @ https://github.com/pauln/arduino-esp32.git#solo-no-mac-crc/1.0.6
    platform:
      - espressif32


esp32:
  board: esp32doit-devkit-v1

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "your encryption key"

ota:
  password: "your ota password"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Xiaomi-Ir Fallback Hotspot"
    password: "your fallback password"

captive_portal:
    
web_server:
  port: 80
  
binary_sensor:
  - platform: gpio
    pin:
      number: GPIO32
      inverted: False
    name: ${friendly_name} Button A
        
  - platform: gpio
    pin:
      number: GPIO33
      inverted: False
    name: ${friendly_name} Button B
                
  - platform: gpio
    pin:
      number: GPIO34
      inverted: False
    name: ${friendly_name} Button C
                
  - platform: gpio
    pin:
      number: GPIO35
      inverted: False
    name: ${friendly_name} Button D

status_led:
  pin:
    number: GPIO18  #Orange LED - flashes for status events
    inverted: True
    
output:
  - platform: gpio
    pin: GPIO23     #Blue LED - Powered on always
    id: PowerLED
    
sensor:
  - platform: wifi_signal
    name: ${friendly_name} WiFi Signal
    
  - platform: uptime
    name: ${friendly_name} Uptime

switch:
  - platform: restart
    name: ${friendly_name} Restart

  - platform: template
    name: ${friendly_name} LG TV Power On
    turn_on_action:
      - remote_transmitter.transmit_lg:
          data: 0x02FD48B7              
          nbits: 32
          transmitter_id: xiaomi
          
mqtt:
  broker: "your broker ip"
  username: "your_mqtt_username"
  password: "your_mqtt_password"
  discovery: True
  
remote_receiver:
  pin:
    number: GPIO27
    inverted: True
  dump: all

remote_transmitter:
  pin:
    number: GPIO26
    inverted: False
  carrier_duty_percent: 50%
  id: xiaomi
